### ISSUE TITLE
Bookdown: group chapters & concepts into parts

### ISSUE THREAD

**Issue by apreshill** [dspatterns/dspatterns-book#10]
https://rstudio4edu.github.io/rstudio4edu-book/book-dress.html#book-parts

Formatting "parts" with CSS: https://github.com/rstudio-education/stat545/blob/d15943d04d7ee5556138c061462da457ec756269/assets/style.css#L171-L180

**Comment by rich-iannone** [comment]
Closed b/c we are using Quarto.
