### ISSUE TITLE
Line numbers for code chunks?

### ISSUE THREAD

**Issue by apreshill** [dspatterns/dspatterns-book#20]
Does this work?
https://bookdown.org/yihui/rmarkdown-cookbook/number-lines.html

**Comment by rich-iannone** [comment]
It does work in Quarto! We get this:

<img width="641" alt="code-numbering" src="https://user-images.githubusercontent.com/5612024/125661297-e9950214-9c5b-4876-a5a0-599df525b487.png">


I used the following CSS:

```
pre.numberSource code > span > a:first-child::before {
  left: -0.5em;
}

pre.numberSource {
  margin-left: 2em;
}
```

The first rule was recommended in the cookbook. The second was my change from 3em to 2em (seems better for numbering from 1-99).

**Comment by apreshill** [comment]
huzzah!

**Comment by rich-iannone** [comment]
Put this in the global CSS file for the Quarto project. Make this work like in here: https://github.com/dspatterns/dspatterns-book/commit/2b353b587dddfac03a10476cacb44090f270a2ed

**Comment by apreshill** [comment]
Decisions:

1. Disable global line numbering in Quarto: https://github.com/dspatterns/dspatterns-book/commit/cab5e931f37f331ee9944509a98622cfafc90e4e (we can still add for individual code chunks)
2. Favor code annotations in Quarto
