### ISSUE TITLE
Use a symbol for HTML details

### ISSUE THREAD

**Issue by apreshill** [dspatterns/dspatterns-book#4]
It should have been more obvious to me, but I wonder if we could use a symbol for the details "code hints". I didn't realize you could click on those. I think the default right arrow that rotates on click is nice, like here:

https://sass-lang.com/documentation/at-rules/extend

Also: explain in text how to use

Accessibility: https://www.hassellinclusion.com/blog/accessible-accordions-part-2-using-details-summary/

**Comment by rich-iannone** [comment]
This confused me for a bit until I opened the rendered book in Chrome (and Firefox) and saw exactly what you meant (no triangle, just the text). Defaults are different on Safari, compared the other two browsers. I found the solution though: use `display: list-item;` in the `summary` element. Now it looks much more press-able!

**Comment by rich-iannone** [comment]
Let's just go with important notes either in the text or in callouts.
