### ISSUE TITLE
 Introductory Data Viz w/ ggplot2 (current Ch. 2) resources 

### ISSUE THREAD

**Issue by apreshill** [dspatterns/dspatterns-book#8]
chapter: https://edr-book.netlify.app/intro-visualization-ggplot.html (new url: https://dspatterns.netlify.app/intro-visualization-ggplot.html)

Wondering about moving this up before dplyr chapter.

Possible project:

https://apreshill.github.io/data-vis-labs-2018/01-eda_hot_dogs.html

**Comment by rich-iannone** [comment]
I'll make the switch happen as a first step. For the second step, I'd love to adapt the above lab into a project for this chapter.

**Comment by rich-iannone** [comment]
The data visualization (ggplot) chapter is now chapter 2 and the data transformation chapter (dplyr) chapter is now chapter 3.

**Comment by apreshill** [comment]
One more: https://apreshill.github.io/data-vis-jamboree-ggplot/jamboree_heart_ggplot.html#overview

**Comment by apreshill** [comment]
Rename chapter: 

Careful counting patterns

This chapter will be all about patterns related to frequencies. How to get them, how to see them, how to tabulate them.

Explore: glimpse/head/tail/nrow/ncol
Understand: tables + viz (distinct / count / geom_col)
Explain: combine with glue for inline code?
Collaborate: use pointblank 
Communicate: gt for tables?

**Comment by rich-iannone** [comment]
Done.
